#! /bin/sh -eu

# Your source directory. Default is the config dir, if it can be found.
SRC_DIR=~/.config/xmonad

# Executable name, from the executable stanza of your cabal file.
# The script will try to guess it if not specified.
EXE_NAME=

##############################################################################

# config

output="$1"

if [ "$SRC_DIR" = "" ]; then
    # look for the config directory, fall back to the old one
    SRC_DIR="${XMONAD_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config/xmonad}}"
    if test -f "$SRC_DIR/build"; then
	:
    else
	SRC_DIR="$HOME/.xmonad"
    fi
fi
cd "$SRC_DIR"

if [ "$EXE_NAME" = "" ]; then
    # try to extract the name of the executable
    # EXE_NAME="$(awk '!done && /^executable / {print $2; done = 1}' *.cabal)"
    # note that there should be only one cabal file or cabal will report a
    # conflict; any utilities should be listed after the xmonad executable
    EXE_NAME=xmonad
fi

# do it to it

d="$(dirname "$output")"
f="$(basename "$output")"
first=0

set -e
cd ${SRC_DIR}
stack build
