#!/bin/bash
# 
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
# 
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# KLUDGES AND WORKAROUNDS
#

# add user path to environment
# This is requred so XMonad recompile will work with cabal isntalled in home directory
. ~/.profile

# Clear xmonad.state before starting xmonad -- otherwise this causes weird
# issues, especially when going between single screen and multi-screen
rm -f ~/.config/xmonad/xmonad.state

#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of 
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
# xcompmgr -n &
picom --dbus --backend glx -f -D 5 --opacity-rule "100:name *= 'i3lock'" -c -o 0.75 &

# pulseaudio &
# Pulse Audio systray
pasystray &

# Clipboard manager systray 
xfce4-clipman &

#
# SCREEN CONFIGURATION
#

# We handle our screen configuration using xrandr. You are likely to want to 
# edit this section to match the specific demands of your setup. The below
# setup is for a Lenovo W520 laptop that sometimes has an external monitor
# hooked up via either VGA or DVI, positioned to the left of the laptop.
#
# Note that you can run xrandr at the command line to get a list of your
# connected screens and find out what names you should use to refer to them.

# If we find that a screen is connected via VGA, activate it and position it
# to the left of the primary screen.
# xrandr | grep 'VGA-1 connected' | ifne xrandr --output VGA-1 --auto --left-of eDP-1

# If we find that a screen is connected via Display Port, activate it and position it
# to the left of the primary screen.

# Office desktop setup
if xrandr | grep '^DP-1-3 connected'; then
    xrandr --output DP-1-3 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 2560x360 --rotate normal
    MONITOR=DP-1-3
fi

# Home desktop setup
if xrandr | grep '^DP-1-1 connected'; then
    xrandr --output DP-1-1 --primary --mode 3440x1440 --pos 0x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 3440x360 --rotate normal
    MONITOR=DP-1-1
fi

# When no external monitor connected then activate builtin as primary
if [ -z "$MONITOR" ]; then
    # Activate primary screen 
    xrandr --output eDP-1 --auto --primary
fi

# LOAD SCREEN BACKGROUNDS
#

# Set a nice background
feh --bg-fill --no-fehbg ~/.wallpapers/haskell-red-noise.png

#
# STARTUP ICON TRAY
#

# We are using polybar to create a small icon tray at the
# top right of the screen. You are likely to want to tweak the
# size of the icons and the width of the tray based upon the
# size of your screen and your xmobar configuration. The goal is
# to make polybar look like it is part of xmobar.
# 
# Edit configuration in ~/.xmonad/stalonetrayrc if needed.
# The one option we set here is the slot size, which you can vary
# depending on your screen setup with STALONETRAY_SLOT_SIZE as shown above
# stalonetray \
MONITOR=${MONITOR} polybar --config=~/.config/polybar/config.ini main &

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
~/bin/switch_layout.sh
setxkbmap -option 'ctrl:nocaps'

# Change the default X cursor away from the "X"
xsetroot -cursor_name left_ptr

# Run OpenForti for VPN access
# openfortigui &
forticlient &

# Bluetooth manager
blueman-applet &

# Network Manager applet
if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable --indicator &
fi

# RingCentral for direct communication
# ringcentral &

# Fire up screensaver
xscreensaver -no-splash &

# Power Management

# Now, finally, start xmonad
#exec xmonad-x86_64-linux
exec xmonad-x86_64-linux
